2024-12-13 09:53:06.266 +08 [12795] LOG:  starting PostgreSQL 16.6 on x86_64-conda-linux-gnu, compiled by x86_64-conda-linux-gnu-cc (conda-forge gcc 13.3.0-1) 13.3.0, 64-bit
2024-12-13 09:53:06.266 +08 [12795] LOG:  listening on IPv6 address "::1", port 5432
2024-12-13 09:53:06.266 +08 [12795] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2024-12-13 09:53:06.268 +08 [12795] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2024-12-13 09:53:06.270 +08 [12798] LOG:  database system was shut down at 2024-12-13 09:53:06 +08
2024-12-13 09:53:06.273 +08 [12795] LOG:  database system is ready to accept connections
2024-12-13 09:54:18.262 +08 [12795] LOG:  received fast shutdown request
2024-12-13 09:54:18.263 +08 [12795] LOG:  aborting any active transactions
2024-12-13 09:54:18.264 +08 [12795] LOG:  background worker "logical replication launcher" (PID 12801) exited with exit code 1
2024-12-13 09:54:18.264 +08 [12796] LOG:  shutting down
2024-12-13 09:54:18.265 +08 [12796] LOG:  checkpoint starting: shutdown immediate
2024-12-13 09:54:18.273 +08 [12796] LOG:  checkpoint complete: wrote 43 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.003 s, sync=0.003 s, total=0.010 s; sync files=11, longest=0.001 s, average=0.001 s; distance=241 kB, estimate=241 kB; lsn=0/14CB150, redo lsn=0/14CB150
2024-12-13 09:54:18.276 +08 [12795] LOG:  database system is shut down
2024-12-13 11:45:39.288 +08 [49743] LOG:  starting PostgreSQL 16.6 on x86_64-conda-linux-gnu, compiled by x86_64-conda-linux-gnu-cc (conda-forge gcc 13.3.0-1) 13.3.0, 64-bit
2024-12-13 11:45:39.288 +08 [49743] LOG:  listening on IPv6 address "::1", port 5432
2024-12-13 11:45:39.288 +08 [49743] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2024-12-13 11:45:39.289 +08 [49743] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2024-12-13 11:45:39.291 +08 [49747] LOG:  database system was shut down at 2024-12-13 11:45:36 +08
2024-12-13 11:45:39.294 +08 [49743] LOG:  database system is ready to accept connections
2024-12-13 11:46:04.856 +08 [49825] ERROR:  extension "vector" is not available
2024-12-13 11:46:04.856 +08 [49825] DETAIL:  Could not open extension control file "/home/dnth/Desktop/pgsql-search/.pixi/envs/default/share/extension/vector.control": No such file or directory.
2024-12-13 11:46:04.856 +08 [49825] HINT:  The extension must first be installed on the system where PostgreSQL is running.
2024-12-13 11:46:04.856 +08 [49825] STATEMENT:  CREATE EXTENSION IF NOT EXISTS vector
2024-12-13 11:46:04.860 +08 [49825] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2024-12-13 11:46:04.860 +08 [49825] STATEMENT:  
	            DROP TABLE IF EXISTS image_metadata;
	
	            CREATE TABLE image_metadata (
	                image_id INTEGER PRIMARY KEY,
	                coco_url TEXT,
	                caption TEXT,
	                recaption TEXT,
	                image_filepath TEXT,
	                img_emb vector(512)
	            )
	            
2024-12-13 11:50:36.543 +08 [50140] ERROR:  extension "vector" is not available
2024-12-13 11:50:36.543 +08 [50140] DETAIL:  Could not open extension control file "/home/dnth/Desktop/pgsql-search/.pixi/envs/default/share/extension/vector.control": No such file or directory.
2024-12-13 11:50:36.543 +08 [50140] HINT:  The extension must first be installed on the system where PostgreSQL is running.
2024-12-13 11:50:36.543 +08 [50140] STATEMENT:  CREATE EXTENSION IF NOT EXISTS vector
2024-12-13 11:50:36.548 +08 [50140] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2024-12-13 11:50:36.548 +08 [50140] STATEMENT:  
	            DROP TABLE IF EXISTS image_metadata;
	
	            CREATE TABLE image_metadata (
	                image_id INTEGER PRIMARY KEY,
	                coco_url TEXT,
	                caption TEXT,
	                recaption TEXT,
	                image_filepath TEXT,
	                img_emb vector(512)
	            )
	            
2024-12-13 11:50:39.391 +08 [49745] LOG:  checkpoint starting: time
2024-12-13 11:51:21.896 +08 [51634] ERROR:  extension "vector" is not available
2024-12-13 11:51:21.896 +08 [51634] DETAIL:  Could not open extension control file "/home/dnth/Desktop/pgsql-search/.pixi/envs/default/share/extension/vector.control": No such file or directory.
2024-12-13 11:51:21.896 +08 [51634] HINT:  The extension must first be installed on the system where PostgreSQL is running.
2024-12-13 11:51:21.896 +08 [51634] STATEMENT:  CREATE EXTENSION IF NOT EXISTS vector
2024-12-13 11:51:21.900 +08 [51634] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2024-12-13 11:51:21.900 +08 [51634] STATEMENT:  
	            DROP TABLE IF EXISTS image_metadata;
	
	            CREATE TABLE image_metadata (
	                image_id INTEGER PRIMARY KEY,
	                coco_url TEXT,
	                caption TEXT,
	                recaption TEXT,
	                image_filepath TEXT,
	                img_emb vector(512)
	            )
	            
2024-12-13 11:52:14.217 +08 [49745] LOG:  checkpoint complete: wrote 947 buffers (5.8%); 0 WAL file(s) added, 0 removed, 0 recycled; write=94.811 s, sync=0.012 s, total=94.826 s; sync files=317, longest=0.001 s, average=0.001 s; distance=4329 kB, estimate=4329 kB; lsn=0/18C9428, redo lsn=0/18C93F0
2024-12-13 12:00:39.407 +08 [49745] LOG:  checkpoint starting: time
2024-12-13 12:01:42.278 +08 [49745] LOG:  checkpoint complete: wrote 626 buffers (3.8%); 1 WAL file(s) added, 0 removed, 0 recycled; write=62.845 s, sync=0.005 s, total=62.871 s; sync files=99, longest=0.001 s, average=0.001 s; distance=6929 kB, estimate=6929 kB; lsn=0/1F8DC20, redo lsn=0/1F8DBE8
2024-12-13 12:10:39.391 +08 [49745] LOG:  checkpoint starting: time
2024-12-13 12:11:26.076 +08 [49745] LOG:  checkpoint complete: wrote 465 buffers (2.8%); 0 WAL file(s) added, 0 removed, 1 recycled; write=46.676 s, sync=0.003 s, total=46.685 s; sync files=40, longest=0.001 s, average=0.001 s; distance=3102 kB, estimate=6547 kB; lsn=0/2295490, redo lsn=0/2295458
2024-12-13 12:13:15.510 +08 [49743] LOG:  received fast shutdown request
2024-12-13 12:13:15.510 +08 [49743] LOG:  aborting any active transactions
2024-12-13 12:13:15.511 +08 [49743] LOG:  background worker "logical replication launcher" (PID 49752) exited with exit code 1
2024-12-13 12:13:15.511 +08 [49745] LOG:  shutting down
2024-12-13 12:13:15.512 +08 [49745] LOG:  checkpoint starting: shutdown immediate
2024-12-13 12:13:15.515 +08 [49745] LOG:  checkpoint complete: wrote 0 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.001 s, total=0.005 s; sync files=0, longest=0.000 s, average=0.000 s; distance=0 kB, estimate=5892 kB; lsn=0/2295540, redo lsn=0/2295540
2024-12-13 12:13:15.520 +08 [49743] LOG:  database system is shut down
2024-12-13 12:13:35.252 +08 [59446] LOG:  starting PostgreSQL 16.6 on x86_64-conda-linux-gnu, compiled by x86_64-conda-linux-gnu-cc (conda-forge gcc 13.3.0-1) 13.3.0, 64-bit
2024-12-13 12:13:35.252 +08 [59446] LOG:  listening on IPv6 address "::1", port 5432
2024-12-13 12:13:35.252 +08 [59446] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2024-12-13 12:13:35.253 +08 [59446] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2024-12-13 12:13:35.256 +08 [59451] LOG:  database system was shut down at 2024-12-13 12:13:29 +08
2024-12-13 12:13:35.260 +08 [59446] LOG:  database system is ready to accept connections
2024-12-13 12:15:56.894 +08 [59840] FATAL:  database "retrieval_db" does not exist
2024-12-13 12:17:49.511 +08 [60011] FATAL:  database "retrieval_db" does not exist
2024-12-13 12:18:35.312 +08 [59449] LOG:  checkpoint starting: time
2024-12-13 12:20:55.048 +08 [59449] LOG:  checkpoint complete: wrote 1393 buffers (8.5%); 1 WAL file(s) added, 0 removed, 0 recycled; write=139.699 s, sync=0.011 s, total=139.737 s; sync files=324, longest=0.001 s, average=0.001 s; distance=7574 kB, estimate=7574 kB; lsn=0/1C0D208, redo lsn=0/1BF46F8
2024-12-13 14:08:36.592 +08 [59449] LOG:  checkpoint starting: time
2024-12-13 14:09:23.476 +08 [59449] LOG:  checkpoint complete: wrote 468 buffers (2.9%); 0 WAL file(s) added, 0 removed, 0 recycled; write=46.876 s, sync=0.004 s, total=46.885 s; sync files=41, longest=0.001 s, average=0.001 s; distance=3177 kB, estimate=7134 kB; lsn=0/1F0EC40, redo lsn=0/1F0EC08
2024-12-13 14:13:34.718 +08 [59446] LOG:  received fast shutdown request
2024-12-13 14:13:34.719 +08 [59446] LOG:  aborting any active transactions
2024-12-13 14:13:34.720 +08 [59446] LOG:  background worker "logical replication launcher" (PID 59455) exited with exit code 1
2024-12-13 14:13:34.720 +08 [59449] LOG:  shutting down
2024-12-13 14:13:34.720 +08 [59449] LOG:  checkpoint starting: shutdown immediate
2024-12-13 14:13:34.723 +08 [59449] LOG:  checkpoint complete: wrote 0 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.001 s, total=0.003 s; sync files=0, longest=0.000 s, average=0.000 s; distance=0 kB, estimate=6421 kB; lsn=0/1F0ECF0, redo lsn=0/1F0ECF0
2024-12-13 14:13:34.726 +08 [59446] LOG:  database system is shut down
2024-12-13 14:21:16.560 +08 [69473] LOG:  starting PostgreSQL 16.6 on x86_64-conda-linux-gnu, compiled by x86_64-conda-linux-gnu-cc (conda-forge gcc 13.3.0-1) 13.3.0, 64-bit
2024-12-13 14:21:16.560 +08 [69473] LOG:  listening on IPv6 address "::1", port 5432
2024-12-13 14:21:16.560 +08 [69473] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2024-12-13 14:21:16.562 +08 [69473] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2024-12-13 14:21:16.564 +08 [69476] LOG:  database system was shut down at 2024-12-13 14:21:16 +08
2024-12-13 14:21:16.567 +08 [69473] LOG:  database system is ready to accept connections
2024-12-13 14:21:22.437 +08 [69554] LOG:  starting PostgreSQL 16.6 on x86_64-conda-linux-gnu, compiled by x86_64-conda-linux-gnu-cc (conda-forge gcc 13.3.0-1) 13.3.0, 64-bit
2024-12-13 14:21:22.438 +08 [69554] LOG:  could not bind IPv6 address "::1": Address already in use
2024-12-13 14:21:22.438 +08 [69554] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2024-12-13 14:21:22.438 +08 [69554] LOG:  could not bind IPv4 address "127.0.0.1": Address already in use
2024-12-13 14:21:22.438 +08 [69554] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2024-12-13 14:21:22.438 +08 [69554] WARNING:  could not create listen socket for "localhost"
2024-12-13 14:21:22.438 +08 [69554] FATAL:  could not create any TCP/IP sockets
2024-12-13 14:21:22.439 +08 [69554] LOG:  database system is shut down
2024-12-13 14:21:31.638 +08 [69477] PANIC:  could not create file "pg_wal/xlogtemp.69477": No such file or directory
2024-12-13 14:21:31.703 +08 [69473] LOG:  WAL writer process (PID 69477) was terminated by signal 6: Aborted
2024-12-13 14:21:31.703 +08 [69473] LOG:  terminating any other active server processes
2024-12-13 14:21:31.703 +08 [69473] LOG:  all server processes terminated; reinitializing
2024-12-13 14:21:31.703 +08 [69473] LOG:  could not open directory "base": No such file or directory
2024-12-13 14:21:31.703 +08 [69473] LOG:  could not open directory "pg_tblspc": No such file or directory
2024-12-13 14:21:31.704 +08 [69473] PANIC:  could not open file "global/pg_control": No such file or directory
2024-12-13 14:21:55.811 +08 [69676] LOG:  starting PostgreSQL 16.6 on x86_64-conda-linux-gnu, compiled by x86_64-conda-linux-gnu-cc (conda-forge gcc 13.3.0-1) 13.3.0, 64-bit
2024-12-13 14:21:55.811 +08 [69676] LOG:  listening on IPv6 address "::1", port 5432
2024-12-13 14:21:55.811 +08 [69676] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2024-12-13 14:21:55.812 +08 [69676] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2024-12-13 14:21:55.814 +08 [69679] LOG:  database system was shut down at 2024-12-13 14:21:55 +08
2024-12-13 14:21:55.816 +08 [69676] LOG:  database system is ready to accept connections
2024-12-13 14:22:47.287 +08 [70092] FATAL:  database "retrieval_db" does not exist
2024-12-13 14:24:03.763 +08 [70449] LOG:  starting PostgreSQL 16.6 on x86_64-conda-linux-gnu, compiled by x86_64-conda-linux-gnu-cc (conda-forge gcc 13.3.0-1) 13.3.0, 64-bit
2024-12-13 14:24:03.764 +08 [70449] LOG:  could not bind IPv6 address "::1": Address already in use
2024-12-13 14:24:03.764 +08 [70449] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2024-12-13 14:24:03.764 +08 [70449] LOG:  could not bind IPv4 address "127.0.0.1": Address already in use
2024-12-13 14:24:03.764 +08 [70449] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2024-12-13 14:24:03.764 +08 [70449] WARNING:  could not create listen socket for "localhost"
2024-12-13 14:24:03.764 +08 [70449] FATAL:  could not create any TCP/IP sockets
2024-12-13 14:24:03.765 +08 [70449] LOG:  database system is shut down
2024-12-13 14:24:45.570 +08 [70616] FATAL:  could not open file "global/pg_filenode.map": No such file or directory
2024-12-13 14:24:56.014 +08 [69676] LOG:  could not open file "postmaster.pid": No such file or directory
2024-12-13 14:24:56.014 +08 [69676] LOG:  performing immediate shutdown because data directory lock file is invalid
2024-12-13 14:24:56.014 +08 [69676] LOG:  received immediate shutdown request
2024-12-13 14:24:56.014 +08 [69676] LOG:  could not open file "postmaster.pid": No such file or directory
2024-12-13 14:24:56.021 +08 [69676] LOG:  database system is shut down
2024-12-13 14:25:01.548 +08 [70710] LOG:  starting PostgreSQL 16.6 on x86_64-conda-linux-gnu, compiled by x86_64-conda-linux-gnu-cc (conda-forge gcc 13.3.0-1) 13.3.0, 64-bit
2024-12-13 14:25:01.548 +08 [70710] LOG:  listening on IPv6 address "::1", port 5432
2024-12-13 14:25:01.548 +08 [70710] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2024-12-13 14:25:01.549 +08 [70710] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2024-12-13 14:25:01.553 +08 [70713] LOG:  database system was shut down at 2024-12-13 14:25:01 +08
2024-12-13 14:25:01.557 +08 [70710] LOG:  database system is ready to accept connections
2024-12-13 14:26:06.585 +08 [70710] LOG:  received fast shutdown request
2024-12-13 14:26:06.587 +08 [70710] LOG:  aborting any active transactions
2024-12-13 14:26:06.588 +08 [70710] LOG:  background worker "logical replication launcher" (PID 70716) exited with exit code 1
2024-12-13 14:26:06.588 +08 [70711] LOG:  shutting down
2024-12-13 14:26:06.589 +08 [70711] LOG:  checkpoint starting: shutdown immediate
2024-12-13 14:26:06.620 +08 [70711] LOG:  checkpoint complete: wrote 1342 buffers (8.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.016 s, sync=0.014 s, total=0.033 s; sync files=314, longest=0.001 s, average=0.001 s; distance=7301 kB, estimate=7301 kB; lsn=0/1BB0180, redo lsn=0/1BB0180
2024-12-13 14:26:06.624 +08 [70710] LOG:  database system is shut down
2024-12-13 14:34:22.883 +08 [72118] LOG:  starting PostgreSQL 16.6 on x86_64-conda-linux-gnu, compiled by x86_64-conda-linux-gnu-cc (conda-forge gcc 13.3.0-1) 13.3.0, 64-bit
2024-12-13 14:34:22.884 +08 [72118] LOG:  listening on IPv6 address "::1", port 5432
2024-12-13 14:34:22.884 +08 [72118] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2024-12-13 14:34:22.885 +08 [72118] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2024-12-13 14:34:22.887 +08 [72122] LOG:  database system was shut down at 2024-12-13 14:34:22 +08
2024-12-13 14:34:22.890 +08 [72118] LOG:  database system is ready to accept connections
2024-12-13 14:35:38.253 +08 [72118] LOG:  received fast shutdown request
2024-12-13 14:35:38.256 +08 [72118] LOG:  aborting any active transactions
2024-12-13 14:35:38.257 +08 [72118] LOG:  background worker "logical replication launcher" (PID 72125) exited with exit code 1
2024-12-13 14:35:38.257 +08 [72120] LOG:  shutting down
2024-12-13 14:35:38.258 +08 [72120] LOG:  checkpoint starting: shutdown immediate
2024-12-13 14:35:38.285 +08 [72120] LOG:  checkpoint complete: wrote 905 buffers (5.5%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.009 s, sync=0.017 s, total=0.028 s; sync files=308, longest=0.002 s, average=0.001 s; distance=4066 kB, estimate=4066 kB; lsn=0/1887618, redo lsn=0/1887618
2024-12-13 14:35:38.289 +08 [72118] LOG:  database system is shut down
2024-12-13 14:35:49.613 +08 [72592] LOG:  starting PostgreSQL 16.6 on x86_64-conda-linux-gnu, compiled by x86_64-conda-linux-gnu-cc (conda-forge gcc 13.3.0-1) 13.3.0, 64-bit
2024-12-13 14:35:49.613 +08 [72592] LOG:  listening on IPv6 address "::1", port 5432
2024-12-13 14:35:49.613 +08 [72592] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2024-12-13 14:35:49.614 +08 [72592] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2024-12-13 14:35:49.617 +08 [72595] LOG:  database system was shut down at 2024-12-13 14:35:49 +08
2024-12-13 14:35:49.620 +08 [72592] LOG:  database system is ready to accept connections
2024-12-13 14:40:49.716 +08 [72593] LOG:  checkpoint starting: time
2024-12-13 14:42:24.575 +08 [72593] LOG:  checkpoint complete: wrote 947 buffers (5.8%); 1 WAL file(s) added, 0 removed, 0 recycled; write=94.708 s, sync=0.016 s, total=94.859 s; sync files=324, longest=0.004 s, average=0.001 s; distance=4329 kB, estimate=4329 kB; lsn=0/1CAFEF8, redo lsn=0/18C93F0
2024-12-13 14:43:16.580 +08 [72592] LOG:  received fast shutdown request
2024-12-13 14:43:16.582 +08 [72592] LOG:  aborting any active transactions
2024-12-13 14:43:16.583 +08 [72592] LOG:  background worker "logical replication launcher" (PID 72598) exited with exit code 1
2024-12-13 14:43:16.583 +08 [72593] LOG:  shutting down
2024-12-13 14:43:16.583 +08 [72593] LOG:  checkpoint starting: shutdown immediate
2024-12-13 14:43:16.591 +08 [72593] LOG:  checkpoint complete: wrote 460 buffers (2.8%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.004 s, sync=0.003 s, total=0.009 s; sync files=27, longest=0.001 s, average=0.001 s; distance=3994 kB, estimate=4296 kB; lsn=0/1CAFFA8, redo lsn=0/1CAFFA8
2024-12-13 14:43:16.594 +08 [72592] LOG:  database system is shut down
2024-12-13 14:43:30.579 +08 [74214] LOG:  starting PostgreSQL 16.6 on x86_64-conda-linux-gnu, compiled by x86_64-conda-linux-gnu-cc (conda-forge gcc 13.3.0-1) 13.3.0, 64-bit
2024-12-13 14:43:30.579 +08 [74214] LOG:  listening on IPv6 address "::1", port 5432
2024-12-13 14:43:30.579 +08 [74214] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2024-12-13 14:43:30.580 +08 [74214] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2024-12-13 14:43:30.582 +08 [74217] LOG:  database system was shut down at 2024-12-13 14:43:30 +08
2024-12-13 14:43:30.584 +08 [74214] LOG:  database system is ready to accept connections
2024-12-13 14:48:31.020 +08 [74215] LOG:  checkpoint starting: time
2024-12-13 14:53:01.081 +08 [74215] LOG:  checkpoint complete: wrote 13275 buffers (81.0%); 0 WAL file(s) added, 0 removed, 5 recycled; write=270.040 s, sync=0.012 s, total=270.062 s; sync files=325, longest=0.001 s, average=0.001 s; distance=92478 kB, estimate=92478 kB; lsn=0/6EDE4D0, redo lsn=0/6EDE498
2024-12-13 15:42:31.902 +08 [74214] LOG:  received fast shutdown request
2024-12-13 15:42:31.907 +08 [74214] LOG:  aborting any active transactions
2024-12-13 15:42:31.908 +08 [74214] LOG:  background worker "logical replication launcher" (PID 74220) exited with exit code 1
2024-12-13 15:42:31.908 +08 [74215] LOG:  shutting down
2024-12-13 15:42:31.908 +08 [74215] LOG:  checkpoint starting: shutdown immediate
2024-12-13 15:42:31.914 +08 [74215] LOG:  checkpoint complete: wrote 0 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.001 s, total=0.006 s; sync files=0, longest=0.000 s, average=0.000 s; distance=0 kB, estimate=83230 kB; lsn=0/6EDE580, redo lsn=0/6EDE580
2024-12-13 15:42:31.925 +08 [74214] LOG:  database system is shut down
2024-12-13 15:42:40.469 +08 [82225] LOG:  starting PostgreSQL 16.6 on x86_64-conda-linux-gnu, compiled by x86_64-conda-linux-gnu-cc (conda-forge gcc 13.3.0-1) 13.3.0, 64-bit
2024-12-13 15:42:40.469 +08 [82225] LOG:  listening on IPv6 address "::1", port 5432
2024-12-13 15:42:40.469 +08 [82225] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2024-12-13 15:42:40.470 +08 [82225] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2024-12-13 15:42:40.472 +08 [82228] LOG:  database system was shut down at 2024-12-13 15:42:40 +08
2024-12-13 15:42:40.478 +08 [82225] LOG:  database system is ready to accept connections
2024-12-13 15:47:40.571 +08 [82226] LOG:  checkpoint starting: time
2024-12-13 15:49:15.327 +08 [82226] LOG:  checkpoint complete: wrote 947 buffers (5.8%); 0 WAL file(s) added, 0 removed, 0 recycled; write=94.737 s, sync=0.015 s, total=94.756 s; sync files=317, longest=0.003 s, average=0.001 s; distance=4329 kB, estimate=4329 kB; lsn=0/18C9428, redo lsn=0/18C93F0
2024-12-13 16:01:59.594 +08 [82225] LOG:  received fast shutdown request
2024-12-13 16:01:59.595 +08 [82225] LOG:  aborting any active transactions
2024-12-13 16:01:59.597 +08 [82225] LOG:  background worker "logical replication launcher" (PID 82231) exited with exit code 1
2024-12-13 16:01:59.597 +08 [82226] LOG:  shutting down
2024-12-13 16:01:59.597 +08 [82226] LOG:  checkpoint starting: shutdown immediate
2024-12-13 16:01:59.600 +08 [82226] LOG:  checkpoint complete: wrote 0 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.001 s, total=0.004 s; sync files=0, longest=0.000 s, average=0.000 s; distance=0 kB, estimate=3897 kB; lsn=0/18C94D8, redo lsn=0/18C94D8
2024-12-13 16:01:59.604 +08 [82225] LOG:  database system is shut down
2024-12-13 16:02:10.009 +08 [101483] LOG:  starting PostgreSQL 16.6 on x86_64-conda-linux-gnu, compiled by x86_64-conda-linux-gnu-cc (conda-forge gcc 13.3.0-1) 13.3.0, 64-bit
2024-12-13 16:02:10.009 +08 [101483] LOG:  listening on IPv6 address "::1", port 5432
2024-12-13 16:02:10.009 +08 [101483] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2024-12-13 16:02:10.011 +08 [101483] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2024-12-13 16:02:10.012 +08 [101486] LOG:  database system was shut down at 2024-12-13 16:02:09 +08
2024-12-13 16:02:10.016 +08 [101483] LOG:  database system is ready to accept connections
2024-12-13 16:07:10.112 +08 [101484] LOG:  checkpoint starting: time
2024-12-13 16:08:52.690 +08 [101484] LOG:  checkpoint complete: wrote 1023 buffers (6.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=102.561 s, sync=0.012 s, total=102.579 s; sync files=323, longest=0.001 s, average=0.001 s; distance=5031 kB, estimate=5031 kB; lsn=0/1978A90, redo lsn=0/1978A58
2024-12-13 17:47:12.133 +08 [101484] LOG:  checkpoint starting: time
2024-12-13 17:47:22.196 +08 [101484] LOG:  checkpoint complete: wrote 101 buffers (0.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=10.054 s, sync=0.003 s, total=10.063 s; sync files=41, longest=0.002 s, average=0.001 s; distance=525 kB, estimate=4580 kB; lsn=0/19FC0A8, redo lsn=0/19FC070
2024-12-18 15:48:05.677 +08 [33301] LOG:  starting PostgreSQL 16.6 on x86_64-conda-linux-gnu, compiled by x86_64-conda-linux-gnu-cc (conda-forge gcc 13.3.0-1) 13.3.0, 64-bit
2024-12-18 15:48:05.677 +08 [33301] LOG:  listening on IPv6 address "::1", port 5432
2024-12-18 15:48:05.677 +08 [33301] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2024-12-18 15:48:05.678 +08 [33301] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2024-12-18 15:48:05.680 +08 [33304] LOG:  database system was shut down at 2024-12-18 15:48:05 +08
2024-12-18 15:48:05.682 +08 [33301] LOG:  database system is ready to accept connections
2024-12-18 15:48:26.544 +08 [33433] FATAL:  database "my_database" does not exist
2024-12-18 15:48:42.535 +08 [33453] FATAL:  database "mylocal_db" does not exist
2024-12-18 15:49:30.939 +08 [33618] FATAL:  database "mylocal_db" does not exist
2024-12-18 15:50:38.734 +08 [33731] FATAL:  database "dnth" does not exist
2024-12-18 15:53:05.726 +08 [33302] LOG:  checkpoint starting: time
2024-12-18 15:54:43.689 +08 [33302] LOG:  checkpoint complete: wrote 979 buffers (6.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=97.948 s, sync=0.011 s, total=97.964 s; sync files=320, longest=0.001 s, average=0.001 s; distance=4722 kB, estimate=4722 kB; lsn=0/192B790, redo lsn=0/192B758
2024-12-18 16:08:05.989 +08 [33302] LOG:  checkpoint starting: time
2024-12-18 16:08:10.422 +08 [33302] LOG:  checkpoint complete: wrote 45 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.426 s, sync=0.003 s, total=4.433 s; sync files=38, longest=0.001 s, average=0.001 s; distance=180 kB, estimate=4268 kB; lsn=0/19588A8, redo lsn=0/1958870
2024-12-18 16:09:36.595 +08 [34022] ERROR:  syntax error at or near "select" at character 30
2024-12-18 16:09:36.595 +08 [34022] STATEMENT:  select * from image_metadata
	select * from image_metadata;
2024-12-18 16:13:05.425 +08 [33302] LOG:  checkpoint starting: time
2024-12-18 16:13:10.461 +08 [33302] LOG:  checkpoint complete: wrote 51 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=5.028 s, sync=0.004 s, total=5.037 s; sync files=45, longest=0.002 s, average=0.001 s; distance=265 kB, estimate=3868 kB; lsn=0/199AEA8, redo lsn=0/199AE70
2024-12-18 16:18:05.561 +08 [33302] LOG:  checkpoint starting: time
2024-12-18 16:18:09.594 +08 [33302] LOG:  checkpoint complete: wrote 41 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.024 s, sync=0.007 s, total=4.034 s; sync files=33, longest=0.005 s, average=0.001 s; distance=211 kB, estimate=3502 kB; lsn=0/19CFE98, redo lsn=0/19CFE60
2024-12-18 16:24:28.358 +08 [34022] ERROR:  relation "filename" does not exist at character 15
2024-12-18 16:24:28.358 +08 [34022] STATEMENT:  select * from filename;
2024-12-18 16:26:44.709 +08 [37455] ERROR:  null value in column "image_filepaths" of relation "image_metadata" violates not-null constraint
2024-12-18 16:26:44.709 +08 [37455] DETAIL:  Failing row contains (1, null, Several horses with riders crossing a body of water.).
2024-12-18 16:26:44.709 +08 [37455] STATEMENT:  
	                INSERT INTO image_metadata (caption)
	                VALUES ($1)
	            
2024-12-18 16:28:05.794 +08 [33302] LOG:  checkpoint starting: time
2024-12-18 16:28:12.436 +08 [33302] LOG:  checkpoint complete: wrote 67 buffers (0.4%); 0 WAL file(s) added, 0 removed, 0 recycled; write=6.636 s, sync=0.005 s, total=6.643 s; sync files=57, longest=0.002 s, average=0.001 s; distance=409 kB, estimate=3193 kB; lsn=0/1A36558, redo lsn=0/1A36520
